language: r

sudo: required

scripts:
    Rscript tests.R

notifications:
  irc:
    channels:
      - "irc.freenode.org#inasafe"
    use_notice: true

  email:
    - helge.dzierzon@plantandfood.co.nz


